
project:
    name: matchEngine
    wiki: https://www.google.fr
    
  
springdoc:
  swagger-ui:
    path: /doc-swagger.html
    

---
#dev config

spring:
  profiles: dev
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/matchingengine?createDatabaseIfNotExist=true&serverTimezone=UTC
    password: root
    
services:
  walletApi: localhost:9090/assets-api-rest/sendPayment



---
#jenkins config
spring:
  profiles: jenkins

  datasource:
    username: root
    url: jdbc:mysql://192.168.33.20:3306/JENKINSmatchingengine?createDatabaseIfNotExist=true&serverTimezone=UTC
    password: example
    initialization-mode: always
  sql:
    init:
      mode: always
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
    defer-datasource-initialization: 'true'
    hibernate:
      ddl-auto: create-drop
    show-sql: 'true'
 
services:
  walletApi: localhost:9090/assets-api-rest/sendPayment
